site: alfaromeousa.com
base_url: https://www.alfaromeousa.com/shopping-tools/directory
generated_by: llm_analyzer
generated_date: '2026-02-03T22:14:56.333227'
confidence: 0.85
notes: ''
selectors:
  search_input:
  - input[placeholder*='zip']
  search_button:
  - button[type='submit']
  view_more_button:
  - button[aria-label='View More']
  dealer_cards:
  - li[class*='dealer']
data_fields:
  name:
    selector: h2
    type: text
    fallback_patterns:
    - h2
    - h3
    - h4
    - '[class*=''name'']'
  address:
    selector: '[class*=''address'']'
    type: text
    fallback_patterns:
    - '[class*=''address'']'
    - '[class*=''location'']'
  phone:
    selector: a[href^='tel:']
    type: href
    attribute: href
    fallback_patterns:
    - a[href^='tel:']
    - '[class*=''phone'']'
  website:
    selector: a[href^='http']
    type: href
    attribute: href
    fallback_patterns:
    - a[href^='http']
    - '[class*=''website'']'
interactions:
  search_sequence:
  - fill_input
  - press_enter
  pagination_type: view_more
  wait_after_search: 4
  wait_after_page_load: 3
  scroll_delay: 0.5
  view_more_delay: 2
  click_delay: 0.3
input_fields:
  zip_code:
    selector: input[placeholder*='zip']
    type: text
    required: true
extraction:
  name_patterns:
  - \w+
  phone_patterns:
  - \(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}
  address_patterns:
  - .+, \w+, \w+ \d{5}
