site: astonmartin.com
base_url: https://www.astonmartin.com/en-us/dealers
generated_by: llm_analyzer
generated_date: '2026-02-03T18:24:50.020824'
confidence: 0.85
notes: The dealer cards are likely to be in a list format with each card having a
  name, address, and phone number.
selectors:
  search_input:
  - input[placeholder*='zip']
  - input[name*='zip']
  search_button:
  - button[type='submit']
  view_more_button:
  - button[class*='load-more']
  dealer_cards:
  - li[class*='dealer']
  - div[class*='dealer']
data_fields:
  name:
    selector: .dealer-name
    type: text
    fallback_patterns:
    - h2
    - h3
    - '[class*=''name'']'
  address:
    selector: .dealer-address
    type: text
    fallback_patterns:
    - '[class*=''address'']'
    - '[class*=''location'']'
  phone:
    selector: .dealer-phone a
    type: href
    attribute: href
    fallback_patterns:
    - a[href^='tel:']
    - '[class*=''phone'']'
  website:
    selector: .dealer-website a
    type: href
    attribute: href
    fallback_patterns:
    - a[href^='http']
    - '[class*=''website'']'
interactions:
  search_sequence:
  - fill_input
  - press_enter
  pagination_type: view_more
  wait_after_search: 4
  wait_after_page_load: 3
  scroll_delay: 0.5
  view_more_delay: 2
  click_delay: 0.3
input_fields:
  zip_code:
    selector: input[placeholder*='zip']
    type: text
    required: true
  radius:
    selector: select[name='radius']
    type: select
    required: false
    default_value: '50'
extraction:
  name_patterns:
  - h2
  - h3
  - '[class*=''name'']'
  phone_patterns:
  - \(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}
  address_patterns:
  - .+?,\s*[A-Za-z\s]+,\s*[A-Z]{2}\s+\d{5}
