site: bugatti.com
base_url: https://www.bugatti.com
generated_by: llm_analyzer
generated_date: '2026-02-03T22:38:50.654573'
confidence: 0.85
notes: ''
selectors:
  search_input:
  - input[placeholder*='zip']
  search_button:
  - button[type='submit']
  view_more_button:
  - button:contains('View More')
  dealer_cards:
  - li[class*='result']
data_fields:
  name:
    selector: h2
    type: text
    fallback_patterns:
    - h3
    - '[class*=''name'']'
  address:
    selector: '[class*=''address'']'
    type: text
    fallback_patterns:
    - '[class*=''location'']'
  phone:
    selector: a[href^='tel:']
    type: href
    attribute: href
    fallback_patterns:
    - '[class*=''phone'']'
  website:
    selector: a[href^='http']
    type: href
    attribute: href
    fallback_patterns:
    - '[class*=''website'']'
interactions:
  search_sequence:
  - fill_input
  pagination_type: view_more
  wait_after_search: 0
  wait_after_page_load: 0
  scroll_delay: 0
  view_more_delay: 2
  click_delay: 0
input_fields:
  zip_code:
    selector: input[placeholder*='zip']
    type: text
    required: true
extraction:
  phone_patterns:
  - \(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}
  address_patterns:
  - .+?,\s*[A-Za-z\s]+,\s*[A-Z]{2}\s+\d{5}
